#only builds the docker container so far
name: publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: docker build . --file Dockerfile --tag hbarni-dcbot:$(date +%s)
